name: a2a
description: An implementation of the Google A2A protocol and SDK for client and server development
version: 3.2.1
repository: https://github.com/shamblett/a2a
homepage: https://github.com/shamblett/a2a

funding:
  - https://www.darticulate.com/#funding

executables:
  a2a_cli_client:

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
    genkit: '^0.9.0'
    oxy: '^0.0.4'
    web: '^1.1.1'
    json_annotation: '^4.9.0'
    colorize: '^3.0.0'
    args: '^2.7.0'
    uuid: '^4.5.2'
    events_emitter: '^0.6.0'
    darto: '^0.0.34'
    darto_types: '^0.0.2'
    mcp_dart: '^1.0.2'
    meta: '^1.16.0'


dev_dependencies:
  test: '^1.28.0'
  lints: '^6.0.0'
  shelf: '^1.4.2'
  shelf_router: '^1.1.4'
  shelf_static: '^1.1.3'
  http: '^1.6.0'
  json_serializable: '^6.11.3'
  build_runner: '^2.10.4'
  json_rpc_2: '^4.0.0'
  stream_channel: '^2.1.4'
  build_test: '^3.5.4'
  build_web_compilers: '^4.4.6'
  llm_dart: '^0.10.5'

topics:
  - ai
  - agents
  - web

screenshots:
    - description: 'Agent 2 Agent(A2A)'
      path: example/screenshots/a2a.jpg
